version: '3.7'

services:
  web:
    restart: always
    container_name: "cms_${INSTANCE_NAME}_web"
    build:
      context: ./cms_src
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/usr/src/cms/staticfiles
      - media_volume:/usr/src/cms/media
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  db:
    restart: always
    container_name: "cms_${INSTANCE_NAME}_db"
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.db

  nginx:
    restart: always
    build: ./nginx
    container_name: "cms_${INSTANCE_NAME}_nginx"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/cms/media
    ports:
      - ${NGINX_PORT}:80
    env_file: .env
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: 
  media_volume:
