version: '3.7'

services:
  web:
    restart: always
    build: 
      context: ./cms_src
      dockerfile: Dockerfile
    volumes:
      - ./cms_src/:/usr/src/cms/
      - ./test_src/:/usr/src/test/
      - ./test_src/fixtures/:/fixtures/
      - ./test_src/media/:/media/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY='o@@xO=jrd=p0^17svmYpw!22-bnm3zz*%y(7=j+p*t%ei-4pi!'
      - SQL_ENGINE=django.db.backends.mysql
      - SQL_DATABASE=personal_cms_db
      - SQL_USER=personal_cms
      - SQL_PASSWORD=N0tTh3D3favlTpAssw0rd
      - SQL_HOST=db
      - SQL_PORT=3306
      - DATABASE=mariadb
      - ENV=dev
    depends_on:
      - db
  db:
    image: mariadb:10.4.5
    restart: always
    volumes:
      - mariadb_data:/var/lib/mariadb/data/
    environment:
      - MYSQL_PASSWORD=N0tTh3D3favlTpAssw0rd
      - MYSQL_DATABASE=personal_cms_db
      - MYSQL_USER=personal_cms
      - MYSQL_RANDOM_ROOT_PASSWORD=true

volumes:
  mariadb_data:
